version: '3'
services:
  todoback:
    image: todobackend
    ports:
      - 3001:3001
    networks:
      - rede-virtual-1
    restart: always
  todofront:
    image: todofrontend
    ports:
      - 3000:3000
    networks:
      - rede-virtual-1
      - rede-virtual-2
    restart: always
    depends_on:
      - todoback
    environment:
      REACT_APP_API_HOST: todoback
  todotests:
    image: todotests
    networks:
      - rede-virtual-2
    restart: always
    depends_on:
      - todofront
      - todoback
    environment:
      FRONT_HOST: todofront

networks:
  rede-virtual-1:
  rede-virtual-2: